// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiRgCua38CkM5fDoHqLc313ZmB0fC9k1E',
    appId: '1:108785760008:android:90a183b228cb006f599ebd',
    messagingSenderId: '108785760008',
    projectId: 'intec-restaurante-f47f6',
    storageBucket: 'intec-restaurante-f47f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUz7nR69mwVDzN06qgqCB8PpYfln42sdY',
    appId: '1:108785760008:ios:e89e768f7598337c599ebd',
    messagingSenderId: '108785760008',
    projectId: 'intec-restaurante-f47f6',
    storageBucket: 'intec-restaurante-f47f6.firebasestorage.app',
    iosBundleId: 'com.example.intecRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUz7nR69mwVDzN06qgqCB8PpYfln42sdY',
    appId: '1:108785760008:ios:e89e768f7598337c599ebd',
    messagingSenderId: '108785760008',
    projectId: 'intec-restaurante-f47f6',
    storageBucket: 'intec-restaurante-f47f6.firebasestorage.app',
    iosBundleId: 'com.example.intecRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCr3kqcbrVcY11mH1V6PRJ9DR3aR-R4Ps',
    appId: '1:108785760008:web:ffb509745d1b8528599ebd',
    messagingSenderId: '108785760008',
    projectId: 'intec-restaurante-f47f6',
    authDomain: 'intec-restaurante-f47f6.firebaseapp.com',
    storageBucket: 'intec-restaurante-f47f6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCr3kqcbrVcY11mH1V6PRJ9DR3aR-R4Ps',
    appId: '1:108785760008:web:7448e3fd013ff19e599ebd',
    messagingSenderId: '108785760008',
    projectId: 'intec-restaurante-f47f6',
    authDomain: 'intec-restaurante-f47f6.firebaseapp.com',
    storageBucket: 'intec-restaurante-f47f6.firebasestorage.app',
  );

}